# Generated by Django 5.0.7 on 2024-08-19 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timesheetdetails',
            name='client_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='users.client'),
            preserve_default=False,
        ),
    ]
