# Generated by Django 5.0.7 on 2024-08-19 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_activity_project_timesheetdetails_client_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetdetails',
            name='process_name',
        ),
    ]
