# Generated by Django 5.0.7 on 2024-08-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='client_ids',
            field=models.ManyToManyField(related_name='customusers', to='users.client'),
        ),
    ]
