# Generated by Django 5.0.7 on 2024-08-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_client_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='client_ids',
        ),
        migrations.AddField(
            model_name='customuser',
            name='client_ids',
            field=models.JSONField(blank=True, default=list, verbose_name=models.IntegerField()),
        ),
    ]
