# Generated by Django 5.0.7 on 2024-09-03 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_client_ids_customuser_client_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetdetails',
            name='activity_name',
            field=models.ForeignKey(default=31, on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='users.activity'),
        ),
    ]
